# Generated by Django 4.0.1 on 2022-02-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='higher_date',
            new_name='hire_date',
        ),
    ]
